### ISSUE TITLE
Message about the end of orders is delivered twice

### ISSUE THREAD

**Issue by pbasista** [vacuumlabs/obedbot#48]
For some reason, messages about the end of orders (handled by `endOfOrders` function in `src/slack.js`) are delivered two times into the `#obedy` Slack channel:

![endoforders](https://user-images.githubusercontent.com/1535892/27916764-5e5ed288-626a-11e7-86d1-9458cfe26990.png)

The same thing happens with the messages which are sent when saving a new user (from function `saveUser` in `src/utils.js`).

**Comment by kubik369** [comment]
This should be resolved, @jurom left the old server running after migration and obedbot ran on both servers at the same time and because it uses web api for the messages, it did not really clash with each other :)
