### ISSUE TITLE
Add hamka ordering

### ISSUE THREAD

**Issue by misogl** [vacuumlabs/obedbot#61]
We want to replace mizza with hamka. Obedbot should:
1. collect orders (soup is mandatory, 5 menu items - some of them can have multiple options)
2. parse menu (you can use http://hamka.sk/ajax/ajax_obj.php with form data `data:{"den":"13.12.2017"}`)

**Comment by syslo** [comment]
Was there official voting? I liked  Lombardi much more :cry: .
